version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./mnt/data/images:/images:ro
    ports:
      - "5824:80"
    depends_on:
      - "ui"
      - "api"
    environment:
      TZ: America/Denver
  ui:
    image: node:22
    working_dir: /app/ui
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./ui:/app/ui
    environment:
      TZ: America/Denver
      UID: ${UID}
      GID: ${GID}
  api:
    build:
      context: api
    working_dir: /app/api
    stop_signal: SIGINT # https://github.com/docker/compose/issues/4199#issuecomment-426109482
    command: uvicorn main:fastapi_app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./api:/app/api
      - ./mnt/data:/data
      - ./mnt/log:/var/log/corganize/api
    environment:
      UID: ${UID}
      GID: ${GID}
      TZ: America/Denver
      DIFFUSION_URL: http://atlas:7859
