version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "5824:80"
    depends_on:
      - "ui"
      - "api"
    environment:
      TZ: America/Denver
  ui:
    image: node:21
    working_dir: /app/ui
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./ui:/app/ui
    environment:
      TZ: America/Denver
  api:
    image: corganize:latest
    build:
      context: api
    working_dir: /app/api
    stop_signal: SIGINT # https://github.com/docker/compose/issues/4199#issuecomment-426109482
    command: uvicorn main:fastapi_app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./api:/app/api
      - ./mnt/data:/data
      - ./mnt/log:/var/log/corganize/api
    environment:
      TZ: America/Denver
      POSTGRES_PASSWORD: CHANGEME
      DIFFUSION_BEE_URL: http://atlas:5825
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb #shared memory size
    environment:
      POSTGRES_PASSWORD: CHANGEME
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d/:ro
      - ./mnt/data/postgres:/var/lib/postgresql/data
