plugins:
  - "@trivago/prettier-plugin-sort-imports"
printWidth: 120
singleQuote: false
importOrder:
  - "\/.*types$"
  - "\/.*state$"
  - "\/.*apiclient$"
  - ".*\/utilities\/.*"
  - "^[.].*(?<!css)$" # relative dependencies (except css)
  - ".*css$" # CSS files
importOrderSeparation: true
importOrderSortSpecifiers: true
